language: node_js

node_js:
  - lts/*

sudo: required
services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t pandres95/api .;
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    docker push pandres95/api;
    fi
